"""
---
title: Vision Transformer (ViT)
summary: >
 A PyTorch implementation/tutorial of the paper
 "An Image Is Worth 16x16 Words: Transformers For Image Recognition At Scale"
---

#  Vision Transformer (ViT)

This is a [PyTorch](https://pytorch.org) implementation of the paper
[An Image Is Worth 16x16 Words: Transformers For Image Recognition At Scale](https://arxiv.org/abs/2010.11929).

Vision transformer applies a pure transformer to images
without any convolution layers.
They split the image into patches and apply a transformer on patch embeddings.
[Patch embeddings](#PathEmbeddings) are generated by applying a simple linear transformation
to the flattened pixel values of the patch.
Then a standard transformer encoder is fed with the patch embeddings, along with a
classification token `[CLS]`.
The encoding on the `[CLS]` token is used to classify the image with an MLP.

When feeding the transformer with the patches, learned positional embeddings are
added to the patch embeddings, because the patch embeddings do not have any information
about where that patch is from.
The positional embeddings are a set of vectors for each patch location that get trained
with gradient descent along with other parameters.

ViTs perform well when they are pre-trained on large datasets.
The paper suggests pre-training them with an MLP classification head and
then using a single linear layer when fine-tuning.
The paper beats SOTA with a ViT pre-trained on a 300 million image dataset.
They also use higher resolution images during inference while keeping the
patch size the same.
The positional embeddings for new patch locations are calculated by interpolating
learning positional embeddings.

Here's [an experiment](experiment.html) that trains ViT on CIFAR-10.
This doesn't do very well because it's trained on a small dataset.
It's a simple experiment that anyone can run and play with ViTs.
"""

import torch
from torch import nn

from transformerlayer import TransformerLayer

class PatchEmbeddings(nn.Module):
    """
    <a id="PatchEmbeddings"></a>

    ## Get patch embeddings,获取patch嵌入

    The paper splits the image into patches of equal size and do a linear transformation
    on the flattened pixels for each patch.
    本文将图像分割成大小相等的图像块，并对每个图像块的展平像素进行线性变换。

    We implement the same thing through a convolution layer, because it's simpler to implement.
    和CNN卷积层实现相同的事情，因为实现更简单。
    """

    def __init__(self, d_model: int, patch_size: int, in_channels: int):
        """
        * `d_model` is the transformer embeddings size，transformer的嵌入尺寸，d_model表示特征数量
        * `patch_size` is the size of the patch，patch的尺寸
        * `in_channels` is the number of channels in the input image (3 for rgb)，输入通道大小，对于RGB图像为3
        """
        super().__init__()

        # We create a convolution layer with a kernel size and and stride length equal to patch size.
        # 建立一个卷积层，卷积核大小和步长等于patch的尺寸
        # This is equivalent to splitting the image into patches and doing a linear
        # 这相当于将图像分割成图像块，并且对每个图像块进行线性变换
        # transformation on each patch.
        # 在每个图像块上进行线性变换
        self.conv = nn.Conv2d(in_channels, d_model, patch_size, stride=patch_size)
        """
        * `in_channels` = 输入通道数量, in_channels = 外部参数in_channels
        * `out_channels` = d_model ,transformer的嵌入尺寸, d_model = 外部参数d_model
        * `kernel_size` = patch_size , patch的尺寸, patch_size = 外部参数patch_size
        * `stride` = patch_size, patch的尺寸, patch_size = 外部参数patch_size
        ##### 用d_model个卷积核，卷积核大小为patch_size，步长为patch_size，
        # h_patch = h // patch_size, w_patch = w // patch_size
        # 卷积后的shape为[batch_size, d_model, h_patch, w_patch]
        """

    def forward(self, x: torch.Tensor):
        """
        * `x` is the input image of shape `[batch_size, channels, height, width]`
        * `x` 输入图像的形状为 `[batch_size, channels, height, width]`
        """
        # Apply convolution layer
        x = self.conv(x)     # 卷积后x.shape = [batch_size, d_model, h, w]
        # Get the shape.
        bs, c, h, w = x.shape
        # Rearrange to shape `[batch_size, patches, d_model]`
        # 先permute再view,因为permute会改变内存而view不改变内存顺序
        x = x.permute(0, 2, 3, 1)
        x = x.view(bs, h * w, c)
        
        # 另一种高效的实现方法
        # x = x.flatten(2).transpose(1, 2)

        # Return the patch embeddings
        return x    # x.shape = [batch_size, patches, d_model]


class LearnedPositionalEmbeddings(nn.Module):
    """
    <a id="LearnedPositionalEmbeddings"></a>

    ## Add parameterized positional encodings 加入参数化位置编码

    This adds learned positional embeddings to patch embeddings.
    """

    def __init__(self, d_model: int, max_len: int = 5_000):
        """
        * `d_model` is the transformer embeddings size, transformer的嵌入尺寸
        * `max_len` is the maximum number of patches, 最大patch数量
        """
        super().__init__()
        # Positional embeddings for each location
        # 位置编码,分配参数内存，shape为[batch_size, max_len, d_model],利用广播机制进行计算
        self.positional_encodings = nn.Parameter(torch.zeros(1, max_len, d_model), requires_grad=True)

    def forward(self, x: torch.Tensor):
        """
        * `x` is the patch embeddings of shape `[batch_size, patches, d_model]`
        """
        # Get the positional embeddings for the given patches
        # x.shape = [batch_size, patches, d_model], x.shape(1) = patches
        pe = self.positional_encodings[:, :x.shape[1], :]
        # Add to patch embeddings and return
        return x + pe


class ClassificationHead(nn.Module):
    """
    <a id="ClassificationHead"></a>

    ## MLP Classification Head,多层感知机分类头

    This is the two layer MLP head to classify the image based on `[CLS]` token embedding.
    # 两层感知机分类头
    [CLS] token embedding是transformer最后一层的输出
    CLS token：可以 attention 到 所有 patch，所以它逐层变成了一个 “全局信息聚合向量”
    也就是说：CLS token 的输出，本质上是整张图像的“语义摘要”
    """
    def __init__(self, d_model: int, n_hidden: int, n_classes: int):
        """
        * `d_model` is the transformer embedding size
        * `n_hidden` is the size of the hidden layer，隐藏层大小
        * `n_classes` is the number of classes in the classification task，分类任务的类别数量
        """
        super().__init__()
        # First layer，第一层 d_model -> n_hidden
        self.linear1 = nn.Linear(d_model, n_hidden)
        # Activation ,激活函数
        self.act = nn.ReLU()
        # Second layer ，第二层 n_hidden -> n_classes
        self.linear2 = nn.Linear(n_hidden, n_classes)

    def forward(self, x: torch.Tensor):
        """
        * `x` is the transformer encoding for `[CLS]` token
        """
        # First layer and activation
        x = self.act(self.linear1(x))
        # Second layer
        x = self.linear2(x)

        return x


class VisionTransformer(nn.Module):
    """
    ## Vision Transformer，ViT class

    This combines the [patch embeddings](#PatchEmbeddings),
    [positional embeddings](#LearnedPositionalEmbeddings),
    transformer and the [classification head](#ClassificationHead).
    四部分组成
                        *`patch_embedding`
                        *`positional_embedding`
                        *`transformer_layers`
                        *`classification head`
    """
    def __init__(self, 
                 transformer_layer: TransformerLayer, 
                 n_layers: int,
                 patch_emb: PatchEmbeddings, 
                 pos_emb: LearnedPositionalEmbeddings,
                 classification: ClassificationHead):
        """
        * `transformer_layer` is a copy of a single [transformer layer](../models.html#TransformerLayer).
         We make copies of it to make the transformer with `n_layers`.
        * `n_layers` is the number of [transformer layers](../models.html#TransformerLayer).
        * `patch_emb` is the [patch embeddings layer](#PatchEmbeddings).
        * `pos_emb` is the [positional embeddings layer](#LearnedPositionalEmbeddings).
        * `classification` is the [classification head](#ClassificationHead).
        """
        super().__init__()
        # Patch embeddings
        self.patch_emb = patch_emb
        self.pos_emb = pos_emb
        # Classification head
        self.classification = classification
        # Make copies of the transformer layer, with `n_layers`
        self.transformer_layers = clone_module_list(transformer_layer, n_layers)

        # `[CLS]` token embedding,一些改进的模型用全局平均池化替换了 `[CLS]` token，x = x.mean(dim=1)
        # transformer_layer.size = d_model, shape = [batch_size = 1, seq_len = 1, d_model]
        self.cls_token_emb = nn.Parameter(torch.randn(1, 1, transformer_layer.size), requires_grad=True)
        # Final normalization layer,最后的归一化层
        self.ln = nn.LayerNorm([transformer_layer.size])

        # Initialize weights
        self.apply(self._init_weights)
        nn.init.trunc_normal_(self.cls_token_emb, std=0.02)
        nn.init.trunc_normal_(self.pos_emb.positional_encodings, std=0.02)


    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            nn.init.trunc_normal_(m.weight, std=0.02)
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, nn.Conv2d):
            nn.init.trunc_normal_(m.weight, std=0.02)
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, nn.LayerNorm):
            nn.init.ones_(m.weight)
            nn.init.zeros_(m.bias)
    
    
    def forward(self, x: torch.Tensor):
        """
        * `x` is the input image of shape `[batch_size, channels, height, width]`
        """
        # Get patch embeddings. This gives a tensor of 
        # shape `[batch_size, patches, d_model]`
        x = self.patch_emb(x)
        # Concatenate the `[CLS]` token embeddings before feeding the transformer
        # 在传入 transformer 之前，先拼接 `[CLS]` token embeddings, [batch_size, 1, d_model]
        cls_token_emb = self.cls_token_emb.expand(x.shape[0], -1, -1)
        # cat in dim=1 ,result shape = [batch_size, patches + 1, d_model]
        x = torch.cat([cls_token_emb, x], dim=1)
        # Add positional embeddings
        x = self.pos_emb(x)

        # Pass through transformer layers with no attention masking,没有掩码
        for layer in self.transformer_layers:
            x = layer(x=x, mask=None)

        # Get the transformer output of the `[CLS]` token (which is the first in the sequence).
        x = x[0]

        # Layer normalization,归一化层
        x = self.ln(x)

        # Classification head, to get logits, 分类头，得到logits
        x = self.classification(x)


        return x


if __name__ == '__main__':
    print('Success!')